# /etc/molly.conf

Hostname = "{{DOMAIN}}"
Port = 1966
Bind = "127.0.0.1"

CertPath = "/etc/letsencrypt/live/{{DOMAIN}}/fullchain.pem"
KeyPath  = "/etc/letsencrypt/live/{{DOMAIN}}/privkey.pem"
ErrorLog = "-"
AccessLog = "-"
DocBase = "/var/run/geminid/{{DOMAIN}}"

# Optional later:
# CGIPaths = [ "/home/gemini/app/public/cgi-bin" ]
