# /skel/etc/syslog/boycottjournald.conf
# To use rsyslog, we must castrate systemd's syslogd/journald "service"
# Grackle installer drops this file in /etc/systemd/journald.conf.d/
#
# This file:
# - disables the 'local' storage of log messages;
# - stops reading /dev/kmsg for kernel messages;
# - and forwards any messages it reads from the system log socket
#   to its own log socket to be picked up by the system's syslog daemon.
[Journal]
Storage=none
ForwardToSyslog=yes
ReadKMsg=no
